{
  "formatVersion": "1.1",
  "component": {
    "url": "../../aws-http/1.3.61-preview/aws-http-1.3.61-preview.module",
    "group": "aws.sdk.kotlin",
    "module": "aws-http",
    "version": "1.3.61-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth-aws",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aws-http-jvm-1.3.61-preview.jar",
          "url": "aws-http-jvm-1.3.61-preview.jar",
          "size": 69003,
          "sha512": "fef6f743a5763bbe10644ff630e94235feed85807722a450f495b832dfce63dc1f795d5e31a68f942567a2ebb22413eafe21a31441e2220a5be58c98b9e8e7e3",
          "sha256": "c619b62b472dd78c80ca366fd9a037a88bbf997dde242cfcfad3e33da0908e88",
          "sha1": "0e9b14271c962219424efdbf71afd01897df615a",
          "md5": "ee5579f2874d3340f3fc10d8520ae600"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth-aws",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aws-http-jvm-1.3.61-preview.jar",
          "url": "aws-http-jvm-1.3.61-preview.jar",
          "size": 69003,
          "sha512": "fef6f743a5763bbe10644ff630e94235feed85807722a450f495b832dfce63dc1f795d5e31a68f942567a2ebb22413eafe21a31441e2220a5be58c98b9e8e7e3",
          "sha256": "c619b62b472dd78c80ca366fd9a037a88bbf997dde242cfcfad3e33da0908e88",
          "sha1": "0e9b14271c962219424efdbf71afd01897df615a",
          "md5": "ee5579f2874d3340f3fc10d8520ae600"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aws-http-jvm-1.3.61-preview-sources.jar",
          "url": "aws-http-jvm-1.3.61-preview-sources.jar",
          "size": 15599,
          "sha512": "f6f933eb67d5ef29d8125fe82c4441898514d9e7e044e930695f01a46d22c9bf309452a1b9daa6a68d5e2e5ecf1b4eaf213c2f0672ca532f0ad552bad282c485",
          "sha256": "87e6df9f73668d646e3fbce84ccc78113f9f5fd141c8dfe983e5eed51ed59109",
          "sha1": "583cfb2a65d4ca8c3885cc3bfe3cea1478513923",
          "md5": "bd4d8c4a49907eead96ff06dd6751636"
        }
      ]
    }
  ]
}
