{
  "formatVersion": "1.1",
  "component": {
    "url": "../../aws-endpoint/1.3.61-preview/aws-endpoint-1.3.61-preview.module",
    "group": "aws.sdk.kotlin",
    "module": "aws-endpoint",
    "version": "1.3.61-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aws-endpoint-jvm-1.3.61-preview.jar",
          "url": "aws-endpoint-jvm-1.3.61-preview.jar",
          "size": 11436,
          "sha512": "b9a830875aae8efdb198cc8a4b6e37dda69a2091d100dea0f287ec00eb73a2f2b108fd38fde18b26caefcba81f8aef20c913e4a5d385d7535cef681442337ed7",
          "sha256": "13b5befd0ada3b7645052ee8663419fb9ec6c294bc3fc844fef6ad8884b8e03b",
          "sha1": "8f21d869b368908773edcbd7788c305e815c70c1",
          "md5": "d4425625528000a57ee02929bfaa76fb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.61-preview"
          }
        }
      ],
      "files": [
        {
          "name": "aws-endpoint-jvm-1.3.61-preview.jar",
          "url": "aws-endpoint-jvm-1.3.61-preview.jar",
          "size": 11436,
          "sha512": "b9a830875aae8efdb198cc8a4b6e37dda69a2091d100dea0f287ec00eb73a2f2b108fd38fde18b26caefcba81f8aef20c913e4a5d385d7535cef681442337ed7",
          "sha256": "13b5befd0ada3b7645052ee8663419fb9ec6c294bc3fc844fef6ad8884b8e03b",
          "sha1": "8f21d869b368908773edcbd7788c305e815c70c1",
          "md5": "d4425625528000a57ee02929bfaa76fb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aws-endpoint-jvm-1.3.61-preview-sources.jar",
          "url": "aws-endpoint-jvm-1.3.61-preview-sources.jar",
          "size": 3170,
          "sha512": "360a660897b28b81a0890582f73ec33eb540d7b89272017d01a7a64cc32d843a5a6259bfbf5de9d82f65180d7573691b81abadcccec06bb18ce3ba2d86d1d2d2",
          "sha256": "59b4f2bf075d34c43e916c78ca4d516c0322bdb3ad5cb2826e3557c34901e78a",
          "sha1": "7fdfc24ec588c477764e8896b20d2e6089054425",
          "md5": "37029d643dac72ff9f95f9dbdb27fe69"
        }
      ]
    }
  ]
}
