{
  "formatVersion": "1.1",
  "component": {
    "group": "aws.sdk.kotlin",
    "module": "version-catalog",
    "version": "1.3.61-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "version-catalog-1.3.61-preview.toml",
          "url": "version-catalog-1.3.61-preview.toml",
          "size": 4497,
          "sha512": "0396083d29058a8005974b7b886a57980c6a89a489f4d4651736a8b40281a1868ddf7d82ca44308cdaf26d5b7f8d5ee79574dd78692d6abb24dd281a15e1729b",
          "sha256": "806dd7a69ec79251db4b9f4842e7c514c7e2dff08916b7518ce0f7af59127a66",
          "sha1": "9132a154b68811c7fbc2aec8a1598d1f77cfe580",
          "md5": "00eb402f710fd20a5389dee0afa1e34b"
        }
      ]
    }
  ]
}
