{
  "formatVersion": "1.1",
  "component": {
    "url": "../../aws-config/1.3.61-preview/aws-config-1.3.61-preview.module",
    "group": "aws.sdk.kotlin",
    "module": "aws-config",
    "version": "1.3.61-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-credentials",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aws-config-jvm-1.3.61-preview.jar",
          "url": "aws-config-jvm-1.3.61-preview.jar",
          "size": 983323,
          "sha512": "c306781cf559830612ea05cd70b84794ff3d25a49bf53d5956160a7c3aedfa64b14617e1d590cd11d2b38ed854aa299e759e5acdcbcc939b0bf3cff49785d566",
          "sha256": "c51f3e21b7d1f6a120dae9cd8fe010ade3ca5fa5a81bbabd1efc353c1b7c354a",
          "sha1": "bc8dc7fc06072451ad68b905736167c399f158fc",
          "md5": "d5cb2c6068f5965086d7f80cbbf5d7ee"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-credentials",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-api",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client-engine-default",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-http",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde-json",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-protocol-core",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-default",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth-aws",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "identity-api",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "smithy-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-defaults",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde-xml",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde-form-url",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-xml-protocols",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-json-protocols",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "aws-config-jvm-1.3.61-preview.jar",
          "url": "aws-config-jvm-1.3.61-preview.jar",
          "size": 983323,
          "sha512": "c306781cf559830612ea05cd70b84794ff3d25a49bf53d5956160a7c3aedfa64b14617e1d590cd11d2b38ed854aa299e759e5acdcbcc939b0bf3cff49785d566",
          "sha256": "c51f3e21b7d1f6a120dae9cd8fe010ade3ca5fa5a81bbabd1efc353c1b7c354a",
          "sha1": "bc8dc7fc06072451ad68b905736167c399f158fc",
          "md5": "d5cb2c6068f5965086d7f80cbbf5d7ee"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aws-config-jvm-1.3.61-preview-sources.jar",
          "url": "aws-config-jvm-1.3.61-preview-sources.jar",
          "size": 232252,
          "sha512": "5d2390de502c9121c1e4f4aff646ad1ee066827f6b7acc66ac5597135ded578c830ad4d256da0fe040b73752c72809eeadc4a874d95c7c9c42533f4f0ad55279",
          "sha256": "2d5ee63e5f596423911a5428e6d09bf7d8aa2db47cdbc23673f19228d8e1ec59",
          "sha1": "38815ea5c126f7502a536ffd769fe6da9d176084",
          "md5": "49c2437b5f4389a2fe599f2860c11883"
        }
      ]
    }
  ]
}
