{
  "formatVersion": "1.1",
  "component": {
    "group": "aws.sdk.kotlin",
    "module": "version-catalog",
    "version": "1.3.58-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "version-catalog-1.3.58-preview.toml",
          "url": "version-catalog-1.3.58-preview.toml",
          "size": 4505,
          "sha512": "069733e967e26fd5000ede07951be1ffd081beff31058da8a139c8c8b70c27f1487bef894f49cdf0fd6c083cb773f7e3f1b6e25bb7eb84281c00b4cbf9671b52",
          "sha256": "3121c9650f43024b24bb5a8f25ce3c66d3af4494a2306f5b6ddfb8bb15df4655",
          "sha1": "0b9b4c139ff340d76317f2d154066654d015cc93",
          "md5": "b8695adf806adb63aa2acc8df6ca8b1a"
        }
      ]
    }
  ]
}
