{
  "formatVersion": "1.1",
  "component": {
    "group": "aws.sdk.kotlin",
    "module": "aws-endpoint",
    "version": "1.3.58-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aws-endpoint-metadata-1.3.58-preview.jar",
          "url": "aws-endpoint-1.3.58-preview.jar",
          "size": 704,
          "sha512": "7331e6425d31585b510d4199554d778a878aec8faf66fedcd1b4eed2844bfac5ac1e27b33d41d0a0d4edd04744149bb758285756ab9baa42f2b517970f0000c0",
          "sha256": "54d63568127e1233276d3c0d5ac27b3c2e828a3a67b318cde0636e4613dc748c",
          "sha1": "23e5235f405ec4fdf8b5b4d870774d6f79989145",
          "md5": "2177a85ff547c2c5fb32ee990d17c48f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "aws-endpoint-kotlin-1.3.58-preview-sources.jar",
          "url": "aws-endpoint-1.3.58-preview-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../aws-endpoint-jvm/1.3.58-preview/aws-endpoint-jvm-1.3.58-preview.module",
        "group": "aws.sdk.kotlin",
        "module": "aws-endpoint-jvm",
        "version": "1.3.58-preview"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../aws-endpoint-jvm/1.3.58-preview/aws-endpoint-jvm-1.3.58-preview.module",
        "group": "aws.sdk.kotlin",
        "module": "aws-endpoint-jvm",
        "version": "1.3.58-preview"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../aws-endpoint-jvm/1.3.58-preview/aws-endpoint-jvm-1.3.58-preview.module",
        "group": "aws.sdk.kotlin",
        "module": "aws-endpoint-jvm",
        "version": "1.3.58-preview"
      }
    }
  ]
}
