{
  "formatVersion": "1.1",
  "component": {
    "group": "aws.sdk.kotlin",
    "module": "aws-http",
    "version": "1.3.61-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth-aws",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aws-http-metadata-1.3.61-preview.jar",
          "url": "aws-http-1.3.61-preview.jar",
          "size": 726,
          "sha512": "e17325bbe88f192e0c023480c2d8d80b3becd2e767c53384da20438ba9036104a6e973cbff85d35d7d3f8474a9badc2108f0d7d997ca3665bb9354db3f24abb6",
          "sha256": "3f4cd5a83d2c72cdff404b43fb8d2858834091a70e571876907998c99a200194",
          "sha1": "70a03158a3a67b0ab321511cd0c76e3d2dcee4a8",
          "md5": "c6a49971d6cc9f224ea030d60cfb57d1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "aws-http-kotlin-1.3.61-preview-sources.jar",
          "url": "aws-http-1.3.61-preview-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../aws-http-jvm/1.3.61-preview/aws-http-jvm-1.3.61-preview.module",
        "group": "aws.sdk.kotlin",
        "module": "aws-http-jvm",
        "version": "1.3.61-preview"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../aws-http-jvm/1.3.61-preview/aws-http-jvm-1.3.61-preview.module",
        "group": "aws.sdk.kotlin",
        "module": "aws-http-jvm",
        "version": "1.3.61-preview"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../aws-http-jvm/1.3.61-preview/aws-http-jvm-1.3.61-preview.module",
        "group": "aws.sdk.kotlin",
        "module": "aws-http-jvm",
        "version": "1.3.61-preview"
      }
    }
  ]
}
