{
  "formatVersion": "1.1",
  "component": {
    "url": "../../aws-endpoint/1.3.58-preview/aws-endpoint-1.3.58-preview.module",
    "group": "aws.sdk.kotlin",
    "module": "aws-endpoint",
    "version": "1.3.58-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aws-endpoint-jvm-1.3.58-preview.jar",
          "url": "aws-endpoint-jvm-1.3.58-preview.jar",
          "size": 11242,
          "sha512": "36647efe673528a00170de7be8303429a3c3079b5045aeabb344633f055f7492e3f0ccb669a02a48352d3647d963397aea83849fc7677458c57c6f73fddbfea2",
          "sha256": "21fe62b67f46fb8888e832a0457ab94ef52ff7c139a91c79182feb6e9e0ebc91",
          "sha1": "6ef3e481539595542d8fc98869deac38b4b561a5",
          "md5": "7d3ea3876c55753bcd1bf1c1828e2e4d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.58-preview"
          }
        }
      ],
      "files": [
        {
          "name": "aws-endpoint-jvm-1.3.58-preview.jar",
          "url": "aws-endpoint-jvm-1.3.58-preview.jar",
          "size": 11242,
          "sha512": "36647efe673528a00170de7be8303429a3c3079b5045aeabb344633f055f7492e3f0ccb669a02a48352d3647d963397aea83849fc7677458c57c6f73fddbfea2",
          "sha256": "21fe62b67f46fb8888e832a0457ab94ef52ff7c139a91c79182feb6e9e0ebc91",
          "sha1": "6ef3e481539595542d8fc98869deac38b4b561a5",
          "md5": "7d3ea3876c55753bcd1bf1c1828e2e4d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aws-endpoint-jvm-1.3.58-preview-sources.jar",
          "url": "aws-endpoint-jvm-1.3.58-preview-sources.jar",
          "size": 3067,
          "sha512": "291f1a8ff35259e5539bc66921a5dcd07b7fef500ecb4df04397a9bbbc67efecce7c903e81b1ff3c4d9a05182408b8a901bbef8de67a6aef15d6a8d4843fddd1",
          "sha256": "82009958b18927665f1d8280ca08d55e6728c536be114b78b90c9691f867c0b4",
          "sha1": "acc4179d247b3360c56098fae7f4448703ee1a79",
          "md5": "4fecd2f1523874e4df7c0a8ac9ccd60b"
        }
      ]
    }
  ]
}
