{
  "formatVersion": "1.1",
  "component": {
    "url": "../../georoutes/1.3.58-preview/georoutes-1.3.58-preview.module",
    "group": "aws.sdk.kotlin",
    "module": "georoutes",
    "version": "1.3.58-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-config",
          "version": {
            "requires": "1.3.58-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.58-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.58-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "smithy-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-api",
          "version": {
            "requires": "1.3.17"
          }
        }
      ],
      "files": [
        {
          "name": "georoutes-jvm-1.3.58-preview.jar",
          "url": "georoutes-jvm-1.3.58-preview.jar",
          "size": 2830813,
          "sha512": "4c8422cdd70484144d2b8b1030f703735071f662e3c6e6a59911307bbfa79b294d4e9bbd56d8872c30cf2c40e1d8c3bb1f1e5300197c3b4f7a62b213a32109de",
          "sha256": "9b9c3b1d07510d6917b5b0908d355163e03067499492f611216cf9991ccc029a",
          "sha1": "bdee19d680c94736cd25f716120ebd71e81f9972",
          "md5": "e5b611e072f4ba403dc23c549c6198dc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-config",
          "version": {
            "requires": "1.3.58-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.58-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.58-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "smithy-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-api",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-credentials",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-http",
          "version": {
            "requires": "1.3.58-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-json-protocols",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-protocol-core",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-default",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth-aws",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client-engine-default",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "identity-api",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde-json",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-defaults",
          "version": {
            "requires": "1.3.17"
          }
        }
      ],
      "files": [
        {
          "name": "georoutes-jvm-1.3.58-preview.jar",
          "url": "georoutes-jvm-1.3.58-preview.jar",
          "size": 2830813,
          "sha512": "4c8422cdd70484144d2b8b1030f703735071f662e3c6e6a59911307bbfa79b294d4e9bbd56d8872c30cf2c40e1d8c3bb1f1e5300197c3b4f7a62b213a32109de",
          "sha256": "9b9c3b1d07510d6917b5b0908d355163e03067499492f611216cf9991ccc029a",
          "sha1": "bdee19d680c94736cd25f716120ebd71e81f9972",
          "md5": "e5b611e072f4ba403dc23c549c6198dc"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "georoutes-jvm-1.3.58-preview-sources.jar",
          "url": "georoutes-jvm-1.3.58-preview-sources.jar",
          "size": 514766,
          "sha512": "3062fb35f185ff8075665d604bae108a91b626fe0f883388cf341b340dba2bfaa601f4af8e806390f1daef3fb60b798a2ec2d79b46beb16f68f0bbec48948ee4",
          "sha256": "d2b70ccc9e5a00602b2fa7c0e00c9f4dce58878aba23dc33b85eeeadb55bc80b",
          "sha1": "b45ab5feef651e385cb972b4bdca14a6790730f3",
          "md5": "c1c8c90f6108cc322fa117e67e633f7b"
        }
      ]
    }
  ]
}
