{
  "formatVersion": "1.1",
  "component": {
    "group": "aws.sdk.kotlin",
    "module": "geoplaces",
    "version": "1.3.61-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-config",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.61-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "smithy-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-api",
          "version": {
            "requires": "1.3.17"
          }
        }
      ],
      "files": [
        {
          "name": "geoplaces-metadata-1.3.61-preview.jar",
          "url": "geoplaces-1.3.61-preview.jar",
          "size": 717,
          "sha512": "b22a791a316de4fcfa0f30e5ae4061a39b9edfc948d04fc4d77b4b71a5afd0e02741609585d5c88224c2b30cea2f0e1a0585556a97dd3f3cf9cbad87d5ce96fa",
          "sha256": "edeffb374938bdff4ca6d2c9c77d1c14b0cb73fd883308bc0bde30f6e81135d6",
          "sha1": "a4f3606ab94d4513ab9375bc390cd84d5c65af32",
          "md5": "eb1b4d287ec37a9603f5e54a5fca68f3"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "geoplaces-kotlin-1.3.61-preview-sources.jar",
          "url": "geoplaces-1.3.61-preview-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../geoplaces-jvm/1.3.61-preview/geoplaces-jvm-1.3.61-preview.module",
        "group": "aws.sdk.kotlin",
        "module": "geoplaces-jvm",
        "version": "1.3.61-preview"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../geoplaces-jvm/1.3.61-preview/geoplaces-jvm-1.3.61-preview.module",
        "group": "aws.sdk.kotlin",
        "module": "geoplaces-jvm",
        "version": "1.3.61-preview"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../geoplaces-jvm/1.3.61-preview/geoplaces-jvm-1.3.61-preview.module",
        "group": "aws.sdk.kotlin",
        "module": "geoplaces-jvm",
        "version": "1.3.61-preview"
      }
    }
  ]
}
