{
  "formatVersion": "1.1",
  "component": {
    "group": "aws.sdk.kotlin",
    "module": "version-catalog",
    "version": "1.3.61-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "version-catalog-1.3.61-preview.toml",
          "url": "version-catalog-1.3.61-preview.toml",
          "size": 4505,
          "sha512": "58a48d693a736911acff30150c75e530bffa31c178bbe7074676bc797bfa6845aa121897e226c5fc10b1b611730582b50a1dad842954452139c50857618575ae",
          "sha256": "dba1ce48337a9fdf9592258a5794d7356fb6db2a16b6e5e58b8ab7b7c5d2b878",
          "sha1": "6a6164c8fe87e588b7a5ae8ff9c842b57183e596",
          "md5": "e2ebbb48663d1fec56990bdc617e098c"
        }
      ]
    }
  ]
}
