{
  "formatVersion": "1.1",
  "component": {
    "url": "../../aws-core/1.3.61-preview/aws-core-1.3.61-preview.module",
    "group": "aws.sdk.kotlin",
    "module": "aws-core",
    "version": "1.3.61-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "smithy-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aws-core-jvm-1.3.61-preview.jar",
          "url": "aws-core-jvm-1.3.61-preview.jar",
          "size": 7576,
          "sha512": "b754f5ada0b59e8ddbf43979e51b9196f378b920ba74e098bcadb52f09c710202fb1a47f9701bf693c791e1103153fa707446411617e0dfa9e68bb59046f7bde",
          "sha256": "2aeb996085992e27d7a2a3b4c5be7252a1778bcd15fd2e2734bfbf39fef4bbfc",
          "sha1": "4881c9c6b83293d92a65457774a3859de6830503",
          "md5": "bbb17f753d8f51403711e352052c2bcc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "smithy-client",
          "version": {
            "requires": "1.3.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "aws-core-jvm-1.3.61-preview.jar",
          "url": "aws-core-jvm-1.3.61-preview.jar",
          "size": 7576,
          "sha512": "b754f5ada0b59e8ddbf43979e51b9196f378b920ba74e098bcadb52f09c710202fb1a47f9701bf693c791e1103153fa707446411617e0dfa9e68bb59046f7bde",
          "sha256": "2aeb996085992e27d7a2a3b4c5be7252a1778bcd15fd2e2734bfbf39fef4bbfc",
          "sha1": "4881c9c6b83293d92a65457774a3859de6830503",
          "md5": "bbb17f753d8f51403711e352052c2bcc"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aws-core-jvm-1.3.61-preview-sources.jar",
          "url": "aws-core-jvm-1.3.61-preview-sources.jar",
          "size": 4053,
          "sha512": "c2cf7b74c755c187555d7f6cb57e5a38e25e60803c775bbe4972195f2a2062d747320872cc149afcd8d8a6958310e0ce67c5efbbebce3fd4a59054a13aa92eb9",
          "sha256": "a52bd68f7b93cd60de53b3f365ad35dbf6a67cbb34a50e69e6bb40d7f34f3528",
          "sha1": "0d95320e385360106184b06022920031f59c3ac9",
          "md5": "cdcf423a9cf250b13ec9646301144a9c"
        }
      ]
    }
  ]
}
