name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_AuthSDKUsername: ${{ secrets.SONATYPE_ACCOUNT_USERNAME }}
          ORG_GRADLE_PROJECT_AuthSDKPassword: ${{ secrets.SONATYPE_ACCOUNT_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SONATYPE_ACCOUNT_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SONATYPE_ACCOUNT_GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SONATYPE_ACCOUNT_GPG_KEY_PASSWORD }}
        run: ./gradlew publishAllPublicationsToAuthSDKRepository
