name: Run Unit Tests for Android
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
jobs:
  test-android:
    name: Test Android
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run Unit Tests
        run: |
          ./gradlew testDebugUnitTest

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: library/build/reports/tests/testDebugUnitTest/
          retention-days: 1